[context.production.environment]
HUGO_VERSION = "0.113.0"
HUGO_ENV = "production"

[build]
publish = "public"
command = "hugo --gc --minify"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200